version: '3.2'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/php-apache/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
    depends_on:
      - mysql
    volumes:
      - ./src:/var/www/html
      - ./docker/php-apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./docker/php-apache/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - "${APACHE_HTTP_PORT}:80"
    stdin_open: true
    tty: true
  mysql:
    image: mariadb:${MYSQL_VERSION}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}